---
date: "2019-05-05T00:00:00+01:00"
draft: false
linktitle: Math Appendices
menu:
  resources:
    parent: Resources
title: List of Math Appendices
toc: true
type: docs
weight: 2
---

| Appendix         | Type | Class |
|------------------|------|------:|
| Budget Constraint for n Goods | Math/Economics | [1.2 class](content/1.2-content/#budget-constraint-for-n-goods) |
| Material on Preferences | Math/Economics | [1.3 class](/content/1.3-content/#appendix-1-material-on-preferences) |
| Steepness & Indifference Curves For Neutrals | Math/Economics | [1.3 class](/content/1.3-content/#assumptions-of-well-behaved-preferences) |
| Derivation of MRS Equation (as ratio of marginal utilities) | Proof | [1.3 class](/content/1.3-content/#derivation-of-mrs-equation-as-ratio-of-marginal-utilities) |
| Utility Functions and PMTs | Math | [1.3 class](/content/1.3-content/#utility-functions-and-pmts) | 
| Graphing Indifference Curves | Math | [1.3 class](/class/1.3-content/#graphing-indifference-curves) | 
| Utility Functions for Perfect Substitutes | Math | [1.3 class](/content/1.3-content/#utility-functions-for-perfect-substitutes) | 
| Utility Functions for Perfect Complements | Math | [1.3 class](/content/1.3-content/#utility-functions-for-perfect-complements) | 
| Cobb-Douglas Functions | Math | [1.3 class](/content/1.3-content/#cobb-douglas-functions) | | Solving the Constrained Optimization Problem with Calculus | Math | [1.4 class](/content/1.4-content/#solving-the-constrained-optimization-problem-with-calculus) | 
| Example Demand Functions | Math | [1.6 class](/content/1.6-content/#math-appendix) | 
| Example Applications of Consumer Theory Models | Applications | [1.7 class](/class/1.7-content/#example-applications-of-consumer-theory-models) | 
| Derivation of MRTS Equation (as ratio of marginal products) | Proof | [2.2 class](/content/2.2-content/#derivation-of-mrts-equation-as-ratio-of-marginal-products) | 
| Solving the Firm’s Problem in One Step | Math | [2.2 class](/content/2.2-content/#solving-the-firms-problem-in-one-step) | 
| The Geometry of Short-Run Production | Math/Economics | [2.2 class](/content/2.2-content/#the-geometry-of-short-run-production) | 
| The Relationship Between Marginal and Average | Math/Economics | [2.2 class](/content/2.2-content/#the-relationship-between-marginal-and-average) | 
| A Change in Relative Factor Prices | Applications | [2.3 class](/content/2.3-content/#a-change-in-relative-factor-prices) | 
| Improvements in Technology | Applications | [2.3 class](/content/2.3-content/#improvements-in-technology) |